# 服务器 配置
server:
  # 服务器端口（https）
  port: 443
  ssl:
    # SSL 配置文件的地址（本项目是使用 jdk KeyTool 生产）（开发时请妥善保管）
    key-store: classpath:config/cert/demo_xuxiaowei_com_cn.jks
    # SSL 文件的密码（开发时请妥善保管）
    key-store-password: aaaaaa
#
# Spring Boot 配置
spring:
  #
  # 数据库 配置
  datasource:
    # 数据库 驱动名称（包括包名）
    # 如果使用 com.mysql.jdbc.Driver，控制台会出现警告：
    # Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'.
    # The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
    # 加载类`com.mysql.jdbc.Driver'。 这已被弃用。
    # 新的驱动程序类是`com.mysql.cj.jdbc.Driver'。 驱动程序通过SPI自动注册，通常不需要手动加载驱动程序类。
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库 URL（URL后面的参数不是必须的，需要根据数据库版本、MySQL驱动版本进行调整；demo：数据库名，useSSL：关闭数据库的SSL连接，serverTimezone：时区设置为东8区）
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&serverTimezone=GMT%2B8
    # 数据库 用户名
    username: root
    # 数据库 密码
    password: root
  #
  # Thymeleaf 配置
  thymeleaf:
    # 是否启用模板缓存（开发时推荐关闭，防止内容已修改，而页面显示内容为历史缓存）
    cache: false
#
# MyBatis Plus 配置
mybatis-plus:
  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法（XML 中有自定义实现），需要进行该配置，告诉 Mapper 所对应的 XML 文件位置。
  # 必须配置（否则出现：org.apache.ibatis.binding.BindingException: Invalid bound statement (not found)）
  mapper-locations: classpath:mapper/*.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，
  # 而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）。
  type-aliases-package: cn.com.xuxiaowei.demo.entity
  # 枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性，
  # 具体使用请结合 枚举注入（https://mp.baomidou.com/guide/enum.html） 查看。
  type-enums-package: cn.com.xuxiaowei.demo.enums
  global-config:
    db-config:
      # 逻辑已删除值,(逻辑删除下有效，默认值：1)
      logic-delete-value: 1
      # 逻辑未删除值,(逻辑删除下有效，默认值：0)
      logic-not-delete-value: 0
#
# 日志 配置
logging:
  level:
    # web 日志扫描
    web: debug
    # 项目（本项目的包结构） 日志扫描
    cn.com.xuxiaowei: debug
